# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20170531_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
