# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='detailuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='detailuser',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='detailuser',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
