# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailuser',
            name='phone',
            field=models.CharField(max_length=9),
        ),
    ]
