# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170510_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailuser',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='detailuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
