# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedaccount',
            name='twitter_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
