# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170512_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccount',
            name='twitter_screen_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
