# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_linkedaccount_twitter_screen_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedaccount',
            old_name='twitter_token',
            new_name='twitter_user_name',
        ),
        migrations.AddField(
            model_name='linkedaccount',
            name='twitter_image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
