# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170519_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccount',
            name='last_tweet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
